"""add service name

Revision ID: 903d85871d02
Revises: ac7d16f14fe8
Create Date: 2024-07-13 22:59:10.306893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '903d85871d02'
down_revision: Union[str, None] = 'ac7d16f14fe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_context_records', sa.Column('service_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_context_records', 'service_name')
    # ### end Alembic commands ###
